#!/usr/bin/env node
// build.mjs — single-file build for 1977.
// Reads src/game.html (the editable source), resolves INLINE markers by
// pasting file contents or encoding assets as base64 data URIs, and writes
// the result to `index.html` (the shipped artifact players open in a browser).
//
// Requires Node 18+. No npm install. No network.
//
// Marker forms (all inside <script> or <style>):
//   /* INLINE:FILE path/from/repo/root */
//   /* INLINE:ASSET path CONST name MIME audio/wav */       -> const name = 'data:audio/wav;base64,...'
//   /* INLINE:SFXR path CONST name */                       -> const name = <parsed JSON sfxr params>
//   /* INLINE:VERSION */                                     -> const BUILD_VERSION = '<stamp>'
//
// Markers are single-line. The script replaces the marker line and any
// previously-generated block immediately below it (delimited by
// `/* /INLINE */`) so builds are idempotent.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, dirname, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC  = resolve(ROOT, 'src/game.html');
const OUT  = resolve(ROOT, 'index.html');

const MIME = {
  '.wav': 'audio/wav', '.mp3': 'audio/mpeg', '.ogg': 'audio/ogg',
  '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg',
  '.gif': 'image/gif', '.svg': 'image/svg+xml', '.json': 'application/json',
  '.js':  'text/javascript', '.css': 'text/css',
};

function readFileFromRepo(p) {
  const abs = resolve(ROOT, p);
  return readFileSync(abs, 'utf8');
}

function readBinaryFromRepo(p) {
  const abs = resolve(ROOT, p);
  return readFileSync(abs);
}

function buildVersion() {
  const pkg = { version: '0.3.0-gsplat' };
  const stamp = new Date().toISOString().slice(0, 19) + 'Z';
  return `${pkg.version}+${stamp}`;
}

// One regex pulls the marker line AND any previously-inlined block so
// repeated builds don't append duplicates.
const MARKER_RE = /\/\*\s*INLINE:([A-Z]+)\s*([^*]*?)\s*\*\/(?:[\s\S]*?\/\*\s*\/INLINE\s*\*\/)?/g;

function processMarker(kind, args) {
  const parts = args.trim().split(/\s+/);
  switch (kind) {
    case 'FILE': {
      const [path] = parts;
      const body = readFileFromRepo(path).trimEnd();
      return `/* INLINE:FILE ${path} */\n${body}\n/* /INLINE */`;
    }
    case 'ASSET': {
      // INLINE:ASSET <path> CONST <name> MIME <type>
      const path = parts[0];
      const nameIdx = parts.indexOf('CONST');
      const mimeIdx = parts.indexOf('MIME');
      const name = nameIdx >= 0 ? parts[nameIdx + 1] : 'ASSET';
      const mime = mimeIdx >= 0 ? parts[mimeIdx + 1] : (MIME[extname(path)] || 'application/octet-stream');
      const b64  = readBinaryFromRepo(path).toString('base64');
      return `/* INLINE:ASSET ${args} */\nconst ${name} = 'data:${mime};base64,${b64}';\n/* /INLINE */`;
    }
    case 'SFXR': {
      // INLINE:SFXR <path> CONST <name>
      const path = parts[0];
      const nameIdx = parts.indexOf('CONST');
      const name = nameIdx >= 0 ? parts[nameIdx + 1] : 'SFXR_PARAMS';
      const json = JSON.parse(readFileFromRepo(path));
      return `/* INLINE:SFXR ${args} */\nconst ${name} = ${JSON.stringify(json)};\n/* /INLINE */`;
    }
    case 'VERSION': {
      return `/* INLINE:VERSION */\nconst BUILD_VERSION = '${buildVersion()}';\n/* /INLINE */`;
    }
    default:
      throw new Error(`Unknown INLINE kind: ${kind}`);
  }
}

function build() {
  if (!existsSync(SRC)) {
    console.error(`[build] source not found: ${SRC}`);
    process.exit(1);
  }
  const src = readFileSync(SRC, 'utf8');
  let replaced = 0;
  const out = src.replace(MARKER_RE, (_match, kind, args) => {
    replaced++;
    return processMarker(kind, args);
  });
  const banner =
`<!--
  AUTO-GENERATED from src/game.html by build.mjs.
  Do NOT edit this file directly; your changes will be overwritten.
  Run:  node build.mjs
-->
`;
  const final = out.startsWith('<!DOCTYPE html>')
    ? out.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n' + banner.trim())
    : banner + out;
  writeFileSync(OUT, final);
  console.log(`[build] wrote ${OUT}  (${replaced} marker${replaced === 1 ? '' : 's'} resolved)`);
}

build();
